apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-page
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: error-page
  template:
    metadata:
      labels:
        app: error-page
    spec:
      containers:
      - name: error-page
        image: nginx
        volumeMounts:
        - name: error-page-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: error-page-html
        configMap:
          name: error-page-html

